# Abstract

Baseflow is the primary source of water in snow-dominated watersheds for most of the year after the high-volume melt period has passed. The Colorado Front Range relies on low flows that result from late spring and early summer snowmelt for municipal, agricultural, and recreational purposes. Changes in the timing and amount of snowmelt due to climate change will impact water availability for millions of people on the Front Range. This study seeks to find the correlation between winter snow water equivalent (SWE) values and subsequent baseflow characteristics, including any yearly lag between the two variables. Streamflow data from US Geological Survey stations and SWE data from Natural Resource Conservation Service SNOTEL stations were examined for drainage basins of varying latitude, elevation, and area across Colorado. 

In snow-dominated ecosystems, the hydrograph shows a well-defined peak when snowmelt occurs in the spring that is followed by low flows in the fall and winter months. The traditional water year (WY, in the US October 1 through September 30) separates peak melt and baseflow into two different WYs. To reflect the hydrologic processes that are occurring in snow-dominated watersheds, we propose using a melt year (MY) beginning with the onset of snowmelt (the first deviation from baseflow) and ending with the onset of the following year’s snowmelt. We identified the beginning of a MY and extracted the subsequent baseflow values using flow duration curves (FDC). This is a dynamic approach to analyzing the correlation between peak SWE and baseflow.  