# References {-}

Cooper, M. G., Schaperow, J. R., Cooley, S. W., Alam, S., Smith, L. C., & Lettenmaier, D. P. (2018). Climate elasticity of low flows in the Maritime Western U.S. Mountains. Water Resources Research, 54(8), 5602–5619. https://doi.org/10.1029/2018wr022816  

Dierauer, J. R., Whitfield, P. H., & Allen, D. M. (2018). Climate Controls on runoff and low flows in mountain catchments of western North America. Water Resources Research, 54(10), 7495–7510. https://doi.org/10.1029/2018wr023087  

Fassnacht, S. R., and J. E. Derry (2010), Defining similar regions of snow in the Colorado River Basin using self‐organizing maps, Water Resour. Res., 46, W04507, doi:10.1029/2009WR007835. 

Godsey, S. E., Kirchner, J. W., & Tague, C. L. (2013). Effects of changes in winter snowpacks on Summer low flows: Case studies in the Sierra Nevada, California, USA. Hydrological Processes, 28(19), 5048–5064. https://doi.org/10.1002/hyp.9943  

Hammond, J. C., & Kampf, S. K. (2020). Subannual streamflow responses to rainfall and snowmelt inputs in snow‐dominated watersheds of the Western United States. Water Resources Research, 56(4). https://doi.org/10.1029/2019wr026132  

Hinckley, E.-L. S., Ebel, B. A., Barnes, R. T., Anderson, R. S., Williams, M. W., & Anderson, S. P. (2014). Aspect control of Water Movement on hillslopes near the rain-snow transition of the Colorado Front Range. Hydrological Processes, 28(1), 74–85. https://doi.org/10.1002/hyp.9549 

Miller, M. P., Susong, D. D., Shope, C. L., Heilweil, V. M., and Stolp, B. J. (2014), Continuous estimation of baseflow in snowmelt-dominated streams and rivers in the Upper Colorado River Basin: A chemical hydrograph separation approach, Water Resour. Res., 50, 6986– 6999, doi:10.1002/2013WR014939. 

Morán-Tejeda, E., S.R. Fassnacht, A.K.D. Pfohl, A.-J. Collados Lara, M.E. Tedesche, and D. Pulido-Velazquez, 2022. A Proposal for Studying Rain-on-Snow Events: A Case Study from SNOTEL Data in the Southern Rocky Mountains, U.S.A. Proceedings of the 39th IAHR World Congress, 19–24 June 2022, Granada, Spain, p268-273. https://doi.org/10.3850/IAHR-39WC2521716X20221604 

Pfohl, A.K.D., and S.R. Fassnacht, 2023. Evaluating Methods of Streamflow Timing to Approximate Snowmelt Contribution in High-Elevation Mountain Watersheds. Hydrology, 10(4), 75. https://doi.org/10.3390/hydrology10040075 

Smakhtin, V. U. (2001). Low flow hydrology: A Review. Journal of Hydrology, 240(3-4), 147–186. https://doi.org/10.1016/s0022-1694(00)00340-1 